{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-credentials" .Release.Name) }}
{{- $passwords := dict }}
{{- $users := .Values.users }}
{{- $_ := set $users "backup" dict }}

{{- with (index $existingSecret "data") }}
  {{- range $k, $v := . }}
    {{- $_ := set $passwords $k (b64dec $v) }}
  {{- end }}
{{- end }}

{{- range $user, $u := $users }}
  {{- if $u.password }}
    {{- $_ := set $passwords $user $u.password }}
  {{- else if not (index $passwords $user) }}
    {{- $_ := set $passwords $user (randAlphaNum 16) }}
  {{- end }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-credentials
stringData:
  {{- range $user, $u := .Values.users }}
  {{ quote $user }}: {{ quote (index $passwords $user) }}
  {{- end }}

---
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "{{ .Release.Name }}"
spec:
  {{- with .Values.size }}
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volume-template
  {{- end }}
  configuration:
    {{- with $users }}
    users:
      {{- range $name, $u := . }}
      {{ $name }}/password_sha256_hex: {{ sha256sum (index $passwords $name) }}
      {{ $name }}/profile: {{ ternary "readonly" "default" (index $u "readonly" | default false) }}
      {{ $name }}/networks/ip: ["::/0"]
      {{- end }}
    {{- end }}
    profiles:
      readonly/readonly: "1"
    clusters:
      - name: "clickhouse"
        layout:
          shardsCount: {{ .Values.shards }}
          replicasCount: {{ .Values.replicas }}
  {{- with .Values.size }}
  templates:
    volumeClaimTemplates:
      - name: data-volume-template
        spec:
          accessModes:
            - ReadWriteOnce
          {{- with $.Values.storageClass }}
          storageClassName: {{ . }}
          {{- end }}
          resources:
            requests:
              storage: {{ . }}
  {{- end }}
          containers:
            - name: clickhouse
              imagePullPolicy: Always
              image: clickhouse/clickhouse-server:24.2.2.71
              volumeMounts:
                - name: data-volume-template
                  mountPath: /var/lib/clickhouse
                - name: log-volume-template
                  mountPath: /var/log/clickhouse-server
              env:
                - name: CLICKHOUSE_CONFIG
                  value: /etc/clickhouse-server/config.d/force_drop_table.xml
                - name: CLICKHOUSE_LOG_CONFIG
                  value: /etc/clickhouse-server/config.d/z_log_disable.xml
                - name: CLICKHOUSE_QUERY_LOG_TTL
                  value: /etc/clickhouse-server/config.d/query_log_ttl.xml
          volumes:
            - name: config-volume
              configMap:
                name: clickhouse-config

