## @section Common parameters

## @param size Persistent Volume size
## @param shards Number of Clickhouse replicas
## @param replicas Number of Clickhouse shards
## @param storageClass StorageClass used to store the data
##
size: 11Gi
shards: 1
replicas: 2
storageClass: ""

## @section Configuration parameters

## @param users [object] Users configuration
## Example:
## users:
##   user1:
##     password: strongpassword
##   user2:
##     readonly: true
##     password: hackme
##
users: {}

## @section Backup parameters

## @param backup.enabled Enable pereiodic backups
## @param backup.s3Region The AWS S3 region where backups are stored
## @param backup.s3Bucket The S3 bucket used for storing backups
## @param backup.schedule Cron schedule for automated backups
## @param backup.cleanupStrategy The strategy for cleaning up old backups
## @param backup.s3AccessKey The access key for S3, used for authentication
## @param backup.s3SecretKey The secret key for S3, used for authentication
## @param backup.resticPassword The password for Restic backup encryption
backup:
  enabled: false
  s3Region: us-east-1
  s3Bucket: s3.example.org/clickhouse-backups
  schedule: "0 2 * * *"
  cleanupStrategy: "--keep-last=3 --keep-daily=3 --keep-within-weekly=1m"
  s3AccessKey: oobaiRus9pah8PhohL1ThaeTa4UVa7gu
  s3SecretKey: ju3eum4dekeich9ahM1te8waeGai0oog
  resticPassword: ChaXoveekoh6eigh4siesheeda2quai0

image:
  repository: clickhouse/clickhouse-server
  tag: "24.2.2.71"


clickhouse:
  config:
    force_drop_table: |
      <yandex>
        <max_partition_size_to_drop>0</max_partition_size_to_drop>
        <max_table_size_to_drop>0</max_table_size_to_drop>
      </yandex>
    z_log_disable: |
      <clickhouse>
          <asynchronous_metric_log remove="1"/>
          <metric_log remove="1"/>
          <query_views_log remove="0" />
          <part_log remove="1"/>
          <session_log remove="1"/>
          <text_log remove="1" />
          <trace_log remove="1"/>
          <crash_log remove="1"/>
          <opentelemetry_span_log remove="1"/>
          <zookeeper_log remove="1"/>
      </clickhouse>
    query_log_ttl:
      <clickhouse>
          <query_log replace="1">
              <database>system</database>
              <table>query_log</table>
              <engine>ENGINE = MergeTree PARTITION BY (event_date)
                      ORDER BY (event_time)
                      TTL event_date + INTERVAL 7 DAY DELETE
              </engine>
              <flush_interval_milliseconds>7500</flush_interval_milliseconds>
          </query_log>
          <query_thread_log replace="1">
              <database>system</database>
              <table>query_thread_log</table>
              <engine>ENGINE = MergeTree PARTITION BY (event_date)
                      ORDER BY (event_time)
                      TTL event_date + INTERVAL 7 DAY DELETE
              </engine>
              <flush_interval_milliseconds>7500</flush_interval_milliseconds>
          </query_thread_log>
      </clickhouse>

